Street 4191
cyclomedia/streetsmart-aol-widget pull request #92
Opened 2022-02-16 19:13 UTC by gcastaneda-cm

Checks if cycloramas are found in the area and creates an alert message while closing the widget if no recordings were found. Also includes the credential fix for the widget.js to use token instead of username.

2022-02-17 10:09 UTC, gpcboekema requested changes

2022-02-17 10:09 UTC, gpcboekema commented on src/Widget.js
> +                    PanelManager.getInstance().closePanel(this.id + "_panel");
Can we make this alert multi language?

2022-02-18 01:47 UTC, gcastaneda-cm reviewed
Added additional languages to the alert.

2022-02-18 01:47 UTC, gcastaneda-cm commented on src/Widget.js
> +                    PanelManager.getInstance().closePanel(this.id + "_panel");
This should make it multi language.

2022-02-18 09:52 UTC, gpcboekema requested changes

2022-02-21 07:43 UTC, gpcboekema approved these changes

2022-02-23 19:52 UTC, merged